export const tagAliases = [
  {
    name: 'JavaScript',
    alias: ['js', 'javascript'],
  },
  {
    name: 'TypeScript',
    alias: ['ts', 'typescript'],
  },
  { name: 'Python', alias: ['py', 'python'] },
  { name: 'Go', alias: ['go', 'golang'] },
  { name: 'Java', alias: ['java'] },
  { name: 'C', alias: ['c'] },
  {
    name: 'C++',
    alias: ['cpp', 'c++'],
    extensions: ['cpp', 'cc', 'cxx', 'hpp'],
  },
  { name: 'Rust', alias: ['rs', 'rust'] },
  { name: 'Ruby', alias: ['rb', 'ruby'] },
  { name: 'PHP', alias: ['php'] },
  { name: 'JSON', alias: ['json'] },
  { name: 'Bash', alias: ['bash', 'sh'] },
  {
    name: 'YAML',
    alias: ['yml', 'yaml'],
    extensions: ['yml', 'yaml'],
  },
  {
    name: 'HTML',
    alias: ['html', 'htm'],
    extensions: ['html', 'htm'],
  },
  { name: 'CSS', alias: ['css'] },
  { name: 'SQL', alias: ['sql'] },
  {
    name: 'Kotlin',
    alias: ['kt', 'kotlin'],
  },
  { name: 'Swift', alias: ['swift'] },
  {
    name: 'Markdown',
    alias: ['md', 'markdown'],
  },
  // Web development libraries, frameworks and tools
  { name: 'Node.js', alias: ['node', 'nodejs', 'node.js'] },
  { name: 'NPM', alias: ['npm'] },
  { name: 'Yarn', alias: ['yarn'] },
  { name: 'pnpm', alias: ['pnpm'] },
  { name: 'Bun', alias: ['bun'] },
  { name: 'Vite', alias: ['vite'] },
  { name: 'Webpack', alias: ['webpack'] },
  { name: 'Rollup', alias: ['rollup'] },
  { name: 'Parcel', alias: ['parcel'] },
  { name: 'esbuild', alias: ['esbuild'] },
  { name: 'React', alias: ['react', 'reactjs'] },
  { name: 'Svelte', alias: ['svelte'] },
  { name: 'Vue', alias: ['vue', 'vuejs'] },
  { name: 'Angular', alias: ['angular'] },
  { name: 'Next.js', alias: ['next', 'nextjs', 'next.js'] },
  { name: 'Nuxt', alias: ['nuxt', 'nuxtjs'] },
  { name: 'Remix', alias: ['remix'] },
  { name: 'Astro', alias: ['astro'] },
  { name: 'Tailwind CSS', alias: ['tailwind', 'tailwindcss'] },
  { name: 'PostCSS', alias: ['postcss'] },
  { name: 'Deno', alias: ['deno'] },
  { name: 'Electron', alias: ['electron'] },
  { name: 'Vercel', alias: ['vercel'] },
  { name: 'Netlify', alias: ['netlify'] },
  { name: 'Redux', alias: ['redux'] },
  { name: 'MobX', alias: ['mobx'] },
  { name: 'GraphQL', alias: ['graphql'] },
  { name: 'Apollo', alias: ['apollo'] },
  { name: 'Prisma', alias: ['prisma'] },
];
